// [演示专用·统计] 正式项目若不用 uni 统计：删除本 import、下方 uniStatcollectItems / uniStatOptions，以及 createApp 内的 app.use(uniStat, ...)
// #ifdef APP-ANDROID || APP-IOS || WEB || MP-WEIXIN || APP-HARMONY
import { uniStat } from '@/uni_modules/uni-stat/plugin.uts'
// #endif
import App from './App.uvue'

import { createSSRApp } from 'vue'

// 统计配置
const uniStatcollectItems = {
	uniStatPageLog: true
}

const uniStatOptions = {
  enable: process.env.NODE_ENV == 'production',
	debug: false,
	collectItems: uniStatcollectItems,
}

export function createApp() {
  const app = createSSRApp(App)
  // [演示专用·统计] 正式项目删除本块
  // #ifdef APP-ANDROID || APP-IOS || WEB || MP-WEIXIN || APP-HARMONY
  app.use(uniStat, uniStatOptions)
  // #endif
  // app.mixin({
  //   onReady() {
  //     setTimeout(() => {
  //       console.log((this as BasePage).$nativePage!.getDomJson())
  //     }, 100)
  //   }
  // })
  return {
    app
  }
}
// 此注释必须放在此文件的最后一行，用于测试issue#18520
